version: '3.8'

services:
  server:
    build:
      context: .
    environment:
      - NODE_ENV=production
    command: >
      sh -c "if [ $$NODE_ENV = 'production' ]; then
              npm run start;
            else
              npm run start:dev;
            fi"
    ports:
      - 5005:5005
    depends_on:
      - postgres
      - minio
      - redis
    restart: always

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      PGUSER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - 5432
    volumes:
      - ./src/helpers/database/init.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready -h db']
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    command: ['server', '--console-address', ':9001', '/data']
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  minio_data:
  redis_data:
